type Base = HTMLElement

export interface HTMLElementAttrs {
  a: HTMLAnchorElement
  abbr: Base
  address: Base
  area: HTMLAreaElement
  article: Base
  aside: Base
  audio: HTMLAudioElement
  b: Base
  bdi: Base
  bdo: Base
  big: Base
  blockquote: HTMLQuoteElement
  body: HTMLBodyElement
  br: HTMLBRElement
  button: HTMLButtonElement
  canvas: HTMLCanvasElement
  caption: Base
  cite: HTMLQuoteElement
  code: Base
  col: HTMLTableColElement
  colgroup: HTMLTableColElement
  data: HTMLDataElement
  datalist: HTMLDataListElement
  dd: Base
  del: HTMLModElement
  details: HTMLDetailsElement
  dfn: Base
  dialog: HTMLDialogElement
  div: HTMLDivElement
  dl: HTMLDListElement
  dt: Base
  em: Base
  embed: HTMLEmbedElement
  fieldset: HTMLFieldSetElement
  figcaption: Base
  figure: Base
  footer: Base
  form: HTMLFormElement
  h1: HTMLHeadingElement
  h2: HTMLHeadingElement
  h3: HTMLHeadingElement
  h4: HTMLHeadingElement
  h5: HTMLHeadingElement
  h6: HTMLHeadingElement
  header: Base
  hr: HTMLHRElement
  html: HTMLHtmlElement
  i: Base
  iframe: HTMLIFrameElement
  img: HTMLImageElement
  input: HTMLInputElement
  ins: HTMLModElement
  kbd: Base
  label: HTMLLabelElement
  legend: HTMLLegendElement
  li: HTMLLIElement
  main: Base
  map: HTMLMapElement
  mark: Base
  meter: HTMLMeterElement
  nav: Base
  object: HTMLObjectElement
  ol: HTMLOListElement
  optgroup: HTMLOptGroupElement
  option: HTMLOptionElement
  output: HTMLOutputElement
  p: HTMLParagraphElement
  picture: Base
  pre: HTMLPreElement
  progress: HTMLProgressElement
  q: HTMLQuoteElement
  rp: Base
  rt: Base
  ruby: Base
  s: Base
  samp: Base
  section: Base
  select: HTMLSelectElement
  small: Base
  source: HTMLSourceElement
  span: HTMLSpanElement
  strong: Base
  sub: Base
  summary: Base
  sup: Base
  svg: SVGSVGElement
  table: HTMLTableElement
  tbody: HTMLTableSectionElement
  td: HTMLTableCellElement
  template: HTMLTemplateElement
  textarea: HTMLTextAreaElement
  tfoot: HTMLTableSectionElement
  th: HTMLTableCellElement
  thead: HTMLTableSectionElement
  time: HTMLTimeElement
  tr: HTMLTableRowElement
  track: HTMLTrackElement
  u: Base
  ul: HTMLUListElement
  var: Base
  video: HTMLVideoElement
  wbr: Base
}
